# Generated by Django 4.2.3 on 2023-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysafiyas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
